---
title: "LondonCrimeV3"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())



setwd("~/dataScience/projects/repo/crime/code/")

outcomes = read.csv("../input/outcomes20152016.csv", header=T, sep=",", stringsAsFactors=F) 
street = read.csv("../input/street20152016.csv", header=T, sep=",", stringsAsFactors=F) 

names(street)
names(outcomes)


names(street) <- c( "CrimeID"  , "Month"  ,  "Reportedby"    ,  "Fallswithin" ,  
 "Longitude"   ,   "Latitude"     ,      "Location"    ,    "LSOAcode"     ,       
 "LSOAname"     ,        "Crimetype"   ,         "Lastoutcomecategory", "Context" )

names(outcomes)<-c( "CrimeID"  ,   "Month"     ,   "ReportedBy"  ,"FallsWithin" ,"Longitude" ,   "Latitude" ,  
                   "Location"  ,   "LSOACode"   , "LSOAName"   , "OutcomeType"  )    

tail(street)

```

```{r setup, include=FALSE}


#data <- merge(x = outcomes, y = street, by = "Crime.ID", all = TRUE)

library(sqldf)
crimes <-  sqldf("SELECT 
         -- count(*)
          s.Month ,s.Crimetype ,s.Lastoutcomecategory, o.Longitude, o.Latitude 
             FROM street s, outcomes o
             where s.CrimeID = o.CrimeID 
             and  s.Month like '2015%'
            and o.Longitude!=''
         --   and s.rowid <= 20
      --   and s.Crimetype like '%sexual%'
          " )

crimes<-crimes[-which(crimes$Month=="Month"), ] 
crimes<-crimes[-which(crimes$Longitude==""), ] 

```

## feature enginering - juas 

```{r pressure, echo=FALSE}
#library(tidyr)

# specify the new column names:
vars <- c("year", "month")
crimes <- separate(crimes, Month, into = vars, sep = "-")

with(crimes, month.abb[as.integer(crimes$month)])

crimes <- transform(crimes, MonthAbb = month.abb[as.integer(crimes$month)])
#df <- mutate(month = month.abb[month])
crimes$Occurrence.Month = factor(crimes$MonthAbb, 
                                  levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""));

```

### Analysis by monthy

```{r, tidy=T}
by_year_and_crime = crimes %>%
  group_by(MonthAbb, Crimetype) %>% summarise(count=n())

ggplot(data=by_year_and_crime, aes(x=MonthAbb, y=count)) +
  ggtitle("Number of offense insidents 2015") +
  xlab("Year  2015") +
  ylab("Number of incidents") + 
  geom_point(aes(color=Crimetype), size=5.0) + 
  geom_line(aes(color=Crimetype), size=2.0)


```

### Analysis by month

Now let us see how does the offense incidents distribute across 12 months.

```{r, tidy=T}
ggplot(data=crimes, aes(x=MonthAbb, color=Crimetype)) + 
  geom_bar(aes(fill = Crimetype)) + 
  ggtitle("Number of offense insidents across 12 months") +
  xlab("Month (from January to December") +
  ylab("Number of incidents") + 
  theme(legend.position = "bottom") + 
  scale_x_discrete(labels=c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  facet_wrap(~Crimetype, nrow=2)
```


## Analysis of the Where

i dont have any Borough ? - i can inferir them

```{r, tidy=T}
ggplot(data=(crimes %>% filter(year==2015)), aes(x = Crimetype)) + 
  geom_bar(aes(fill = Crimetype)) + 
  ggtitle("The histogram of offense insidents by borough") +
  xlab("Crimetype") +
  ylab("Number of Crimes") + 
  theme(legend.position = "bottom") + 
  scale_x_discrete(labels=c("Bu", "FA", "GL", "GM", "RP", "RO", "M")) +
  facet_wrap(~Borough, nrow=1)
```


### Interative map
Now we analysis the offense by borough in 2015. Since we will use the library "ggmap" to visualize map, we need to first add two columns: 'lon' and 'lat':
```{r, tidy=T}
library(leaflet)

crimes = crimes %>% mutate(lon=Longitude, lat=Latitude)

```

