---
  title: "othersLondonCrime"
output: html_document

---
  
#Before being a Data Scientist, I remind you to: 
  
               
                                              
```{r read, include=FALSE}
format(Sys.time(), "%d-%m-%Y--%H:%M:%S")

rm(list = ls())
library(data.table)
library(ggplot2) # graph
library(plotly)  # grapgh

library(tidyr)   #separate
library(dplyr)#select

library(sqldf) # sql




WIN <- TRUE
if (WIN) {setwd("c:/repos/repo/crime/code/")} else{setwd("~/dataScience/projects/repo/crime/code/")}
if (WIN) {system('dir') } else {system('ls -lh ./../input/' )} 

#path <-'../input/2016-07/2016-07-metropolitan-street.csv'
#path <-'../input/2016-07/2016-07-bedfordshire-street.csv'

#street <-'../input/streetMetropolitan2016.csv'
#out <-'../input/outcomesMetropolitan2016.csv'

allTimePath <-'../input/streetMetropolitan20102015.csv'


s=fread(street, colClasses=c(Longitude="character",Latitude="character"),
        header=T, sep=",", verbose = FALSE, showProgress = FALSE) %>% as.data.frame() # SILENCE

o=fread(out, colClasses=c(Longitude="character",Latitude="character"),
        header=T, sep=",", verbose = FALSE, showProgress = FALSE) %>% as.data.frame() # SILENCE





names(allTimedataset)



rm(list = ls())


# read --------------------------------------------------------------------



readData <- function(path.name, file.name,  missing.types, types) {
  fread(  paste(path.name, file.name, sep="") , 
            colClasses=types,
            na.strings=missing.types, 
          verbose = FALSE, showProgress = TRUE )%>% as.data.frame() 
}





types <- c(
  
'Crime ID'  =    'character',
'Month'               =    'character', 
'Reported by'          =    'NULL',
'Falls within'         =    'NULL',
'Longitude'          =  'integer',    # Month
'Latitude'           =  'integer',    # Month
'Location'           =  'character',    # Month
'LSOA code'            ='character',
'LSOA name'            ='character',
'Crime type'           ='character',
'Last outcome category'='character',
'Context'              ='NULL'

)


missing.types <- c("NA", "")

crime.raw <- readData('../input/', "streetMetropolitan20102015.csv",   missing.types,types  )




names(crime.raw) <- c( "CrimeID"  , "Month"  ,   "Longitude",   "Latitude",      "Location",    "LSOAcode",       
               "LSOAname"     ,        "Crimetype"   ,         "Lastoutcomecategory")


names(o)<- c( "CrimeID"  , "Month"  ,  "Reportedby"    ,  "Fallswithin" ,  
              "Longitude"  ,  "Latitude"  ,  "Location"  ,   "LSOAcode"     , "LSOAname"  , "Outcome")

format(Sys.time(), "%d-%m-%Y--%H:%M:%S")





  
  #Filtering   
  #dataset = filter(dataset, as.integer(year) < 2016)
  
  #subsetting
  #crimes <- subset(e,  # Crimetype =='Drugs',
  #select=c(year, month,  Longitude,Latitude,LSOAcode,LSOAname,Crimetype)) 
```







#data cleaning 


```{r anaysis, include=FALSE}}


  #Cleaning  
row.has.na <- apply(crime.raw, 1, function(x){any(is.na(x))})
sum(row.has.na)
str(row.has.na)

  
crime.raw.void <- crime.raw[row.has.na,]
crime.raw.clean <- crime.raw[!row.has.na,]

require(Amelia)
missmap(crime.raw.void, main="crime.raw.void - Missings Map", 
        col=c("yellow", "black"), legend=FALSE)


 
    
 dataclean = function(dataset) {
    

    dataset<-dataset[-which(dataset$Month=="Month"), ] 

    vars <- c("year", "month")
    dataset <- separate(dataset, Month, into = vars, sep = "-")
    
    return(dataset)
    
  }
  

crime.raw.clean = dataclean(crime.raw.clean) # we remove some duplicate headers



```

#lets  see which types of crimes does not have id 

```{r preprocesing, tidy=T}

barplot(table(crime.raw.clean$Crimetype),
        names.arg =  unique(crime.raw.clean$Crimetype),
        main="Types Crimes recorded in the system", col="black")

barplot(table(crime.raw.void$Crimetype),
        names.arg =  unique(crime.raw.void$Crimetype),
        main="Types crimes don't keep it ", col="black")
# antisocial behaviour is not recorded 
```

#let see how many of the crimes has a positive outcome (for the societe not the offedner)

```{r preprocesing, tidy=T}

    by_type_crime_out = crime.raw.clean %>%   filter( Crimetype == 'Violent crime' )%>%
      group_by(Crimetype, Lastoutcomecategory) %>% summarise(count=n()) 

# Stacked Bar Plot with Colors and Legend
counts <- table( by_type_crime_out$count, by_type_crime_out$Lastoutcomecategory)
barplot(counts, main="outcomes Violets crimes",
  xlab="Number of Violents", col=c("darkblue","red"),
  legend = rownames(counts)) 





```




```{r preprocesing, tidy=T}

so = mergesql(o,s)
drugs = mergesqldrugs(o,s)

sDrugs <- allTimedataset %>% filter( Crimetype == 'Drugs' |  Crimetype == 'Violence and sexual offences')
weapons <- s %>% filter(Crimetype == 'Possession of weapons')
sexual <- s %>% filter(Crimetype == 'Violence and sexual offences')

  showmap(crimes)
  
  showYearCrime(sDrugs)
  showplotYearCrime(sDrugs)
  
  


require(ggmap)

area_map_obj = get_map("LONDON ", zoom = 12, maptype = "toner-background",  source = "stamen")


satellite =get_map("LONDON", zoom = 12,  source = "google", maptype = "satellite")


mapImageData2 <- get_map("LONDON",
    color = "color",
    source = "google",
    maptype = "terrain",
    zoom = 12)

d = drugs %>%     mutate(lon = Longitude, lat = Latitude)
d$lon <- as.numeric (d$lon)
d$lat <- as.numeric (d$lat)
d$Longitude <-  as.numeric (d$Longitude)
d$Latitude <- as.numeric (d$Latitude)

#http://www.bytemining.com/wp-content/uploads/2010/08/r_hpc_II.pdf
#https://www.r-bloggers.com/google-maps-and-ggmap/
 # https://sundeepblue.github.io/7SinsInNYC.html

draw_density_map_of_offenses_for_borough(mapImageData2, d)

#http://gizmodo.com/5941436/how-to-make-a-gif-in-five-easy-steps

draw_density_map_of_offenses_for_borough = function(area_map_obj, d) {
    ggmap(area_map_obj, base_layer = ggplot(aes(x = lon, y = lat), data = d)) + 
        stat_density2d(aes(x = lon, y = lat), data = d, color = "blue", alpha = 0.5) + 
        stat_density2d(aes(x = lon, y = lat, fill = ..level.., alpha = ..level..), 
            bins = 7, geom = "polygon", alpha = 0.3, contour = T, data = d) + 
        scale_fill_gradient(low = "green", high = "red") + facet_wrap(~Crimetype, 
        nrow = 2)
}

```



## Analisys when  

lets see year by crime


```{r anaysis, include=FALSE}}
  

  
  showYearCrime(e)
  showplotYearCrime(e)
```



## fuctions

  
```{r functions cleaning, tidy=T}

 
  
  
  
  #data <- merge(x = outcomes, y = street, by = "Crime.ID", all = TRUE)
  
  mergesql = function(o,s) {
    crimes <-  sqldf("SELECT 
                     -- count(*)
                     s.year, s.month, o.year, o.month, s.Crimetype ,s.Lastoutcomecategory,  o.Longitude, o.Latitude ,o.Outcome
                     FROM s s, o o
                     where s.CrimeID = o.CrimeID 
                     and s.Lastoutcomecategory != o.outcome
                     --   and  s.Month like '2015%'
                     --   and o.Longitude!=''
                     --  and s.rowid <= 20
                     --   and s.Crimetype like '%sexual%'
                     " )
    return(crimes)
  }
  
    mergesqldrugs  = function(o,s) {
    crimes <-  sqldf("SELECT 
                     -- count(*)
                     s.year, s.month,  s.Crimetype ,s.Lastoutcomecategory,  o.Longitude, o.Latitude 
                     FROM s s, o o
                     where s.CrimeID = o.CrimeID 
                      and s.Crimetype ='Drugs'
                     --and s.Lastoutcomecategory != o.outcome
                     --   and  s.Month like '2015%'
                     --   and o.Longitude!=''
                     --  and s.rowid <= 20
                     --   and s.Crimetype like '%sexual%'
                     " )
    return(crimes)
  }
  

  #Cleaning  
  #row.has.na <- apply(dataset, 1, function(x){any(is.na(x))})
  #sum(row.has.na)
  #dataset <- dataset[!row.has.na,]
  
  #Filtering   
  #dataset = filter(dataset, as.integer(year) < 2016)
  
  #subsetting
  #crimes <- subset(e,  # Crimetype =='Drugs',
  #select=c(year, month,  Longitude,Latitude,LSOAcode,LSOAname,Crimetype)) 
```
  
  
```{r functions ploty, tidy=T}
  
  showplotYearCrime = function(dataset) {
    
    by_year_and_crime = dataset %>%
      group_by(year, Crimetype) %>% summarise(count=n())
    
    ggplot(data=by_year_and_crime, aes(x=year, y=count)) +
      ggtitle("Number of offense insidents 2010 2106") +
      xlab("Year  2010 2106") +
      ylab("Number of incidents") + 
      geom_point(aes(color=Crimetype), size=5.0) + 
      geom_line(aes(color=Crimetype), size=2.0)
    
  }
  
  showYearCrime = function(dataset) {
    temp <- dataset %>% select(Crimetype,year)
    #temp <- temp %>% group_by(year,Crimetype) %>% summarise(n=n())
    temp <- temp %>% group_by(year) %>% summarise(n=n())
    
    temp <- na.omit(temp)
    p <- plot_ly(temp, x = year, y = n, name = "Number of crimes by Year")
    p %>%
      add_trace(y = fitted(loess(n ~ year)), x = year) %>%
      layout(title = "Year and Crimes",
             showlegend = FALSE) %>%
      dplyr::filter(n == max(n)) %>%
      layout(annotations = list(x = year, y = n, text = "Peak", showarrow = T))
    
  }
  
  showmap = function(dataset) {
    library(leaflet)
    
    m <- leaflet() %>%
      addTiles() %>%  # Add default OpenStreetMap map tiles
      addMarkers(lng=as.integer(dataset$Longitude), lat=as.integer(dataset$Latitude),
                 popup=dataset$Crimetype,
                 clusterOptions = markerClusterOptions())
    m  # Print the map
  }
  
   factorMonth = function(dataset) {
  dataset$Occurrence.Month = factor(dataset$Occurrence.Month, 
                                  levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""));
	}
	
										   
```
  