---
title: "werewolf"
output: html_document
---
#https://sundeepblue.github.io/7SinsInNYC.html

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(oce)
```

## Moon fase


```{r moon}

par(mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0)) # tighten margins
t <- as.POSIXct("2016-09-01", tz="UTC") + seq(0, 13*28*24*3600, 3600)
f <- moonAngle(t=t, longitude=-63.6, 
                    latitude=44.65)$illuminatedFraction
plot(t, f, type="l", xlab="month of 2015", ylab="Moon fraction")
grid()
```

## valentine


```{r valentine, echo=FALSE}
times <- seq(as.POSIXct("2014-02-14", tz="UTC"), length.out=50, by="year")
library(oce)
fraction <- moonAngle(times, lon=-63, lat=43)$illuminatedFraction
full <- fraction > 0.99
plot(times, fraction, xlab="Year", ylab="Moon Illuminated Fraction",
     col=ifelse(full, "red", "blue"), pch=16, cex=2)

```

## read data
```{r crimes, echo=FALSE}


getwd()
system("ls -lh  ~/dataScience/datasets/data/werewolf/")
setwd("~/dataScience/datasets/data/werewolf/")

library(ff)
library(dplyr)

# since the csv has around 1.1 million lines, we use ffdf for fast loading
t = read.csv.ffdf(file="crime.csv", header=TRUE, 
                  VERBOSE=TRUE, first.rows=10000, next.rows=50000, colClasses=NA)

# convert ffdf type to data.frame for later conversion
t = as.data.frame(t)

# we are only interested in offenses in last 10 years [2006, 2015]
str(t)
t_2015 = filter(t, Occurrence.Year == 2015)
```



```{r crimes, echo=FALSE}

crymes$T
types<-unique(mydata$Text_General_Code)
str(types)


```

